// Map of currency codes to their respective country codes
const CURRENCY_TO_COUNTRY: { [key: string]: string } = {
  USD: "us",
  EUR: "eu",
  GBP: "gb",
  ARS: "ar",
  UAH: "ua",
  HRK: "hr",
  AZN: "az",
  JPY: "jp",
  AUD: "au",
  CAD: "ca",
  CHF: "ch",
  CNY: "cn",
  HKD: "hk",
  NZD: "nz",
  SEK: "se",
  KRW: "kr",
  SGD: "sg",
  NOK: "no",
  MXN: "mx",
  INR: "in",
  RUB: "ru",
  ZAR: "za",
  TRY: "tr",
  BRL: "br",
  TWD: "tw",
  DKK: "dk",
  PLN: "pl",
  THB: "th",
  IDR: "id",
  HUF: "hu",
  CZK: "cz",
  ILS: "il",
  CLP: "cl",
  PHP: "ph",
  AED: "ae",
  COP: "co",
  SAR: "sa",
  MYR: "my",
  RON: "ro",
  BDT: "bd",
  BGN: "bg",
  BHD: "bh",
  BIF: "bi",
  BMD: "bm",
  BND: "bn",
  BOB: "bo",
  BSD: "bs",
  BTN: "bt",
  BWP: "bw",
  BYN: "by",
  BZD: "bz",
  CRC: "cr",
  CUP: "cu",
  CVE: "cv",
  DJF: "dj",
  DOP: "do",
  DZD: "dz",
  EGP: "eg",
  ERN: "er",
  ETB: "et",
  FJD: "fj",
  FKP: "fk",
  FOK: "fo",
  GEL: "ge",
  GGP: "gg",
  GHS: "gh",
  GIP: "gi",
  GMD: "gm",
  GNF: "gn",
  GTQ: "gt",
  GYD: "gy",
  HNL: "hn",
  HTG: "ht",
  IQD: "iq",
  IRR: "ir",
  ISK: "is",
  JMD: "jm",
  JOD: "jo",
  KES: "ke",
  KGS: "kg",
  KHR: "kh",
  KID: "ki",
  KMF: "km",
  KWD: "kw",
  KYD: "ky",
  KZT: "kz",
  LAK: "la",
  LBP: "lb",
  LKR: "lk",
  LRD: "lr",
  LSL: "ls",
  LYD: "ly",
  MAD: "ma",
  MDL: "md",
  MGA: "mg",
  MKD: "mk",
  MMK: "mm",
  MNT: "mn",
  MOP: "mo",
  MRU: "mr",
  MUR: "mu",
  MVR: "mv",
  MWK: "mw",
  MZN: "mz",
  NAD: "na",
  NGN: "ng",
  NIO: "ni",
  NPR: "np",
  OMR: "om",
  PAB: "pa",
  PEN: "pe",
  PGK: "pg",
  PKR: "pk",
  PYG: "py",
  QAR: "qa",
  RSD: "rs",
  RWF: "rw",
  SBD: "sb",
  SCR: "sc",
  SDG: "sd",
  SHP: "sh",
  SLL: "sl",
  SOS: "so",
  SRD: "sr",
  SSP: "ss",
  STN: "st",
  SYP: "sy",
  SZL: "sz",
  TJS: "tj",
  TMT: "tm",
  TND: "tn",
  TOP: "to",
  TTD: "tt",
  TVD: "tv",
  TZS: "tz",
  UGX: "ug",
  UYU: "uy",
  UZS: "uz",
  VES: "ve",
  VND: "vn",
  VUV: "vu",
  WST: "ws",
  XAF: "cm",
  XCD: "ag",
  XOF: "bj",
  XPF: "pf",
  YER: "ye",
  ZMW: "zm",
  ZWL: "zw",
  LTL: "lt",
  LVL: "lv",
  MTL: "mt",
  SIT: "si",
  SKK: "sk",
};

/**
 * Returns a URL to the flag icon for the given currency code
 * Uses Flagcdn which provides consistent sizing and high-quality SVG flags
 * @param currencyCode The ISO 4217 currency code (e.g., "USD", "EUR")
 * @param size The size of the flag image (default: 64)
 * @returns URL to the currency's country flag
 */
export const getCurrencyIcon = (
  currencyCode: string,
  size: number = 64
): string => {
  const countryCode = CURRENCY_TO_COUNTRY[currencyCode.toUpperCase()];

  if (!countryCode) {
    return "https://flagcdn.com/w80/xx.png"; // Generic flag for unknown currencies
  }

  // Flagcdn supports various sizes: w20, w40, w80, w160, w320, w640, w1280, w2560
  const flagSize =
    size <= 20
      ? 20
      : size <= 40
      ? 40
      : size <= 80
      ? 80
      : size <= 160
      ? 160
      : size <= 320
      ? 320
      : 640;

  return `https://flagcdn.com/w${flagSize}/${countryCode}.png`;
};
